package ro.unibuc.prodeng.service;

import java.util.List;
import java.util.function.Supplier;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import ro.unibuc.prodeng.model.UserEntity;
import ro.unibuc.prodeng.monitoring.MonitoringMetricsService;
import ro.unibuc.prodeng.repository.UserRepository;
import ro.unibuc.prodeng.request.CreateUserRequest;
import ro.unibuc.prodeng.response.UserResponse;
import ro.unibuc.prodeng.exception.EntityNotFoundException;

@Service
public class UserService {

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private MonitoringMetricsService metrics;

    private <T> T withDbMetrics(Supplier<T> operation) {
        return metrics == null ? operation.get() : metrics.recordDbOperation(operation);
    }

    private void withDbMetrics(Runnable operation) {
        if (metrics == null) {
            operation.run();
            return;
        }
        metrics.recordDbOperation(operation);
    }

    public List<UserResponse> getAllUsers() {
        return withDbMetrics(() -> userRepository.findAll().stream()
                .map(this::toResponse)
                .toList());
    }

    public UserResponse getUserById(String id) throws EntityNotFoundException {
        return withDbMetrics(() -> {
            UserEntity user = userRepository.findById(id)
                    .orElseThrow(() -> new EntityNotFoundException(id));
            return toResponse(user);
        });
    }

    public UserEntity getUserEntityById(String id) throws EntityNotFoundException {
        return withDbMetrics(() -> userRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException(id)));
    }

    public UserResponse createUser(CreateUserRequest request) {
        return withDbMetrics(() -> {
            if (userRepository.findByEmail(request.email()).isPresent()) {
                throw new IllegalArgumentException("Email already exists: " + request.email());
            }
            UserEntity user = new UserEntity(
                    null, // ID will be generated by the repository
                    request.name(),
                    request.email()
            );
            UserEntity saved = userRepository.save(user);
            if (metrics != null) {
                metrics.recordUserCreated();
            }
            return toResponse(saved);
        });
    }

    public UserResponse changeName(String id, String newName) throws EntityNotFoundException {
        return withDbMetrics(() -> {
            UserEntity existing = userRepository.findById(id)
                    .orElseThrow(() -> new EntityNotFoundException(id));
            UserEntity updated = new UserEntity(existing.id(), newName, existing.email());
            UserEntity saved = userRepository.save(updated);
            return toResponse(saved);
        });
    }

    public void deleteUser(String id) throws EntityNotFoundException {
        withDbMetrics(() -> {
            if (!userRepository.existsById(id)) {
                throw new EntityNotFoundException(id);
            }
            userRepository.deleteById(id);
        });
    }

    public UserResponse getUserByEmail(String email) throws EntityNotFoundException {
        return withDbMetrics(() -> {
            UserEntity user = userRepository.findByEmail(email)
                    .orElseThrow(() -> new EntityNotFoundException(email));
            return toResponse(user);
        });
    }

    public UserEntity getUserEntityByEmail(String email) throws EntityNotFoundException {
        return withDbMetrics(() -> userRepository.findByEmail(email)
                .orElseThrow(() -> new EntityNotFoundException(email)));
    }

    private UserResponse toResponse(UserEntity user) {
        return new UserResponse(
                user.id(),
                user.name(),
                user.email()
        );
    }
}
